
replicaCount: 1
extraEnvVars: []
ipWhitelist: []

serviceAccount:
  create: false
  name: "ecr-proxy"
  annotations: {}

image:
  repository: ghcr.io/giuliocalzolari/ecr-proxy-go
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 256Mi

service:
  type: ClusterIP
  port: 5000
  name: ecr-proxy
  annotations: {}

ingress:
  enabled: false
  path: /
  pathType: Prefix
  hostname: chart-example.local
  annotations: {}
  ingressClassName: nginx
  tls: true
  existingSecret: ""

containerSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault


podSecurityContext:
  fsGroupChangePolicy: Always
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault


extraLabels: {}

autoscaling:
  # -- Enable replica autoscaling settings
  enabled: false
  # -- Minimum replicas for the pod autoscaling
  minReplicas: 1
  # -- Maximum replicas for the pod autoscaling
  maxReplicas: 11
  # -- Percentage of CPU to consider when autoscaling
  targetCPU: "80"
  # -- Percentage of Memory to consider when autoscaling
  targetMemory: ""


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
priorityClassName: ""
