
replicaCount: 1
extraEnvVars: []
  # - name: MY_ENV_VAR
  #   value: my-value
rbac:
  ## If true, create & use RBAC resources
  create: true
  ## Ignored if rbac.create is true
  serviceAccountName: default
  extraRules: []
   # - apiGroups:
   #     - argoproj.io
   #   resources:
   #     - rollouts
   #   verbs:
   #     - get
   #     - watch
   #     - list
   #     - update
   #     - patch

image:
  repository: ghcr.io/giuliocalzolari/ecr-proxy-go
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: IfNotPresent
  args: []
    # - --include-resources=deployments,cronjobs

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 150m
    memory: 256Mi

securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

extraLabels: {}


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
priorityClassName: ""
