# You need to use that account for your dd-agent DaemonSet
{{ if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "ecr-proxy.labels" . | indent 4 }}
  name: {{ template "ecr-proxy.fullname" . }}
{{- end -}}
