name: test
on:
    pull_request:
      branches:
        - master
jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run tests
      run: |
        make test

